import { VibePreset, WallpaperItem } from '../types';

export const VIBE_PRESETS: VibePreset[] = [
  {
    id: 'cyberpunk-lofi',
    title: 'Rainy Cyberpunk Lo-Fi',
    prompt: 'rainy cyberpunk lo-fi city street with neon signs, glowing puddles, and warm cafe window reflections',
    category: 'Futuristic',
    tags: ['Neon', 'Rain', 'Moody', 'Cozy'],
  },
  {
    id: 'studio-ghibli',
    title: 'Ghibli Meadow',
    prompt: 'Studio Ghibli inspired rolling green meadow with wildflowers, fluffy cumulus clouds, and distant sunlit castle',
    category: 'Anime & Art',
    tags: ['Ghibli', 'Whimsical', 'Summer', 'Serene'],
  },
  {
    id: 'deep-space',
    title: 'Minimalist Deep Space',
    prompt: 'deep cosmic nebula with dark starry abyss, iridescent galaxy dust and minimalist crescent planet horizon',
    category: 'Space',
    tags: ['OLED Dark', 'Cosmic', 'Minimal', 'Stars'],
  },
  {
    id: 'tokyo-alley',
    title: 'Tokyo Night Alley 3AM',
    prompt: 'quiet Tokyo back alleyway at 3am, vending machine ambient glow, lanterns, wet asphalt reflections and hanging cables',
    category: 'Urban',
    tags: ['Tokyo', 'Night', 'Cinematic', 'Atmospheric'],
  },
  {
    id: 'nordic-mist',
    title: 'Nordic Foggy Pines',
    prompt: 'foggy misty Scandinavian pine forest with gentle mountain silhouettes, cold blue dawn light and serene lake',
    category: 'Nature',
    tags: ['Forest', 'Fog', 'Calm', 'Nordic'],
  },
  {
    id: 'abstract-glass',
    title: 'Liquid 3D Glass',
    prompt: 'abstract flowing iridescent liquid glass ribbons in organic fluid motion with prismatic caustic light refractions',
    category: 'Abstract',
    tags: ['3D', 'Glass', 'Vibrant', 'Clean'],
  },
  {
    id: 'botanical-gold',
    title: 'Dark Botanical Gold',
    prompt: 'dark midnight botanical lush monstera and eucalyptus leaves with delicate kintsugi liquid gold foil veins',
    category: 'Luxury',
    tags: ['Gold', 'Botanical', 'Dark Mode', 'Elegant'],
  },
  {
    id: 'synthwave-sunset',
    title: 'Retro Synthwave Grid',
    prompt: 'retro 80s outrun synthwave sunset over a neon wireframe horizon with chrome reflections and violet dusk sky',
    category: 'Retro',
    tags: ['80s', 'Outrun', 'Sunset', 'Retro'],
  },
];

// Curated initial 9:16 wallpapers for immediate delight and preview
export const INITIAL_WALLPAPERS: WallpaperItem[] = [
  {
    id: 'init_wp_1',
    title: 'Cyberpunk Skyline Pulse',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1080&h=1920&q=80',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA AI',
    prompt: 'rainy cyberpunk lo-fi street with glowing neon lights and puddles',
    flavor: 'Cinematic wide perspective, dramatic atmospheric lighting, immersive phone wallpaper framing with clear central depth.',
    variationIndex: 0,
    timestamp: Date.now() - 1000 * 60 * 30,
    isRemix: false,
  },
  {
    id: 'init_wp_2',
    title: 'Neon Tokyo Shinjuku Alley',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1080&h=1920&q=80',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA AI',
    prompt: 'rainy cyberpunk lo-fi street with glowing neon lights and puddles',
    flavor: 'Detailed artistic composition, rich textural subtleties, high contrast palette, aesthetic mobile wallpaper.',
    variationIndex: 1,
    timestamp: Date.now() - 1000 * 60 * 25,
    isRemix: false,
  },
  {
    id: 'init_wp_3',
    title: 'Neon Matrix Stream',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1080&h=1920&q=80',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA AI',
    prompt: 'rainy cyberpunk lo-fi street with glowing neon lights and puddles',
    flavor: 'Minimalist and clean layout with elegant negative space at top for phone lockscreen clock and widgets.',
    variationIndex: 2,
    timestamp: Date.now() - 1000 * 60 * 20,
    isRemix: false,
  },
  {
    id: 'init_wp_4',
    title: 'Prismatic Aurora Portal',
    category: 'Abstract',
    url: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=1080&h=1920&q=80',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA AI',
    prompt: 'rainy cyberpunk lo-fi street with glowing neon lights and puddles',
    flavor: 'Intense ambient mood, dynamic volumetric highlights, layered background atmosphere, photorealistic finish.',
    variationIndex: 3,
    timestamp: Date.now() - 1000 * 60 * 15,
    isRemix: false,
  },
];
