import { WallpaperItem } from '../types';

export const PIXELORA_WALLPAPERS: WallpaperItem[] = [
  // ── NATURE (4) ──────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_01',
    title: 'Emerald Bamboo Sanctuary',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'sunlight piercing through serene emerald bamboo grove with gentle morning mist',
    flavor: 'Lush natural lighting with calm morning atmosphere and deep vertical green tones.',
    variationIndex: 0,
    timestamp: 1726000000000,
    downloads: 1420,
    tags: ['Bamboo', 'Lush', 'Calm', 'Green'],
  },
  {
    id: 'pixelora_wp_02',
    title: 'Misty Redwood Veil',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'majestic tall coastal redwoods enveloped in rolling morning coastal fog',
    flavor: 'Moody atmospheric forest with towering vertical scale and soft fog diffusion.',
    variationIndex: 1,
    timestamp: 1726000100000,
    downloads: 980,
    tags: ['Forest', 'Fog', 'Moody', 'Trees'],
  },
  {
    id: 'pixelora_wp_03',
    title: 'Cascading Forest Solitude',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'deep woodland waterfall flowing gracefully over dark mossy stone ledges',
    flavor: 'Cool turquoise water tones with rich forest greens and crisp organic textures.',
    variationIndex: 2,
    timestamp: 1726000200000,
    downloads: 1845,
    tags: ['Waterfall', 'River', 'Greenery', 'Fresh'],
  },
  {
    id: 'pixelora_wp_04',
    title: 'Dewlit Botanical Fronds',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'macro lush tropical palm and monstera leaves glistening with morning dew drops',
    flavor: 'Intricate botanical pattern with deep contrast and natural organic detail.',
    variationIndex: 3,
    timestamp: 1726000300000,
    downloads: 1250,
    tags: ['Leaves', 'Monstera', 'Dew', 'Dark Green'],
  },

  // ── CARS (4) ────────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_05',
    title: 'Cyberpunk GT Night Racer',
    category: 'Cars',
    url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'high-performance sports car parked under glowing neon city rain with wet street reflections',
    flavor: 'Cinematic vehicular lighting, sleek metallic curves, and atmospheric neon dusk.',
    variationIndex: 0,
    timestamp: 1726000400000,
    downloads: 2410,
    tags: ['Supercar', 'Neon', 'Rain', 'Speed'],
  },
  {
    id: 'pixelora_wp_06',
    title: 'Midnight Matte Turbo',
    category: 'Cars',
    url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'stealth matte black modern supercar with aggressive aerodynamic rear diffuser and carbon fiber',
    flavor: 'OLED-friendly dark automotive design with subtle edge reflections.',
    variationIndex: 1,
    timestamp: 1726000500000,
    downloads: 3120,
    tags: ['Matte Black', 'Stealth', 'Hypercar', 'OLED'],
  },
  {
    id: 'pixelora_wp_07',
    title: 'Vintage Sunset Cruiser',
    category: 'Cars',
    url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'classic silver sports coupe bathed in warm golden hour coastal light',
    flavor: 'Warm nostalgic retro aesthetic with polished chrome highlights and sun flares.',
    variationIndex: 2,
    timestamp: 1726000600000,
    downloads: 1670,
    tags: ['Classic', 'Vintage', 'Golden Hour', 'Retro'],
  },
  {
    id: 'pixelora_wp_08',
    title: 'Neon Tunnel Velocity',
    category: 'Cars',
    url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'red LED lightbar tail lights carving streaks through dark futuristic city tunnel',
    flavor: 'Dynamic speed blur, vibrant light trails, and dramatic dark highway mood.',
    variationIndex: 3,
    timestamp: 1726000700000,
    downloads: 2190,
    tags: ['Tunnel', 'Light Trails', 'Futuristic', 'Drive'],
  },

  // ── ANIME (4) ───────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_09',
    title: 'Ghibli Meadow Breeze',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'Studio Ghibli style rolling emerald grassy hillside, fluffy cumulus clouds and gentle breeze',
    flavor: 'Whimsical painted anime aesthetic with vibrant sky gradients and pastoral serenity.',
    variationIndex: 0,
    timestamp: 1726000800000,
    downloads: 3840,
    tags: ['Ghibli', 'Meadow', 'Clouds', 'Dreamy'],
  },
  {
    id: 'pixelora_wp_10',
    title: 'Tokyo Alleyway 3AM',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'rainy Tokyo alley at night with glowing vending machine, red lanterns, and anime reflections',
    flavor: 'Lo-fi cozy anime vibe, warm street lamp glow against wet asphalt.',
    variationIndex: 1,
    timestamp: 1726000900000,
    downloads: 2980,
    tags: ['Tokyo', 'Lo-Fi', 'Rain', 'Lanterns'],
  },
  {
    id: 'pixelora_wp_11',
    title: 'Sakura Twilight Gateway',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'traditional Japanese torii gate surrounded by blossoming pink cherry blossoms at dusk',
    flavor: 'Poetic pastel pink and violet tones with tranquil Japanese cultural scenery.',
    variationIndex: 2,
    timestamp: 1726001000000,
    downloads: 2450,
    tags: ['Sakura', 'Torii', 'Japan', 'Twilight'],
  },
  {
    id: 'pixelora_wp_12',
    title: 'Cyber Ronin Rooftop',
    category: 'Anime',
    url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'futuristic anime cyber samurai overlooking sprawling neon cyberpunk metropolis in rain',
    flavor: 'Dramatic vertical skyscraper framing with rich electric blues and magenta hues.',
    variationIndex: 3,
    timestamp: 1726001100000,
    downloads: 3670,
    tags: ['Cyberpunk', 'Samurai', 'Cityscape', 'Neon'],
  },

  // ── SPACE (4) ───────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_13',
    title: 'Orion Stellar Nursery',
    category: 'Space',
    url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'deep cosmic interstellar nebula with glowing turquoise gas pillars and sparkling newborn stars',
    flavor: 'Mesmerizing deep universe imagery with high-contrast galactic dust filaments.',
    variationIndex: 0,
    timestamp: 1726001200000,
    downloads: 4120,
    tags: ['Nebula', 'Stars', 'Cosmos', 'Galaxy'],
  },
  {
    id: 'pixelora_wp_14',
    title: 'Lunar Obsidian Abyss',
    category: 'Space',
    url: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'crescent moon floating in pitch-black deep space void with subtle crater relief',
    flavor: 'Pure OLED black background with crisp illuminated lunar rim detail.',
    variationIndex: 1,
    timestamp: 1726001300000,
    downloads: 2890,
    tags: ['Moon', 'OLED', 'Minimal Space', 'Dark'],
  },
  {
    id: 'pixelora_wp_15',
    title: 'Saturn Rings Solar Flare',
    category: 'Space',
    url: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'planetary rings curving through cosmos with brilliant solar lens flare and orbital perspective',
    flavor: 'Vast planetary scale with golden atmospheric ring scattering.',
    variationIndex: 2,
    timestamp: 1726001400000,
    downloads: 1950,
    tags: ['Planets', 'Rings', 'Orbit', 'Sunlight'],
  },
  {
    id: 'pixelora_wp_16',
    title: 'Cosmic Event Horizon',
    category: 'Space',
    url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'gravitational lensing around deep space singularity with brilliant accretion disk of light',
    flavor: 'Surreal astrophysical beauty with mesmerizing luminous concentric curves.',
    variationIndex: 3,
    timestamp: 1726001500000,
    downloads: 3340,
    tags: ['Black Hole', 'Gravity', 'Ultraviolet', 'Singularity'],
  },

  // ── MINIMAL (4) ─────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_17',
    title: 'Dune Shadow Rhythms',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'minimalist wind-carved desert sand dune crest with sharp high-contrast light and shadow',
    flavor: 'Elegant organic minimalism, clean monochrome gradient and warm earth tones.',
    variationIndex: 0,
    timestamp: 1726001600000,
    downloads: 1780,
    tags: ['Desert', 'Dune', 'Shadow', 'Clean'],
  },
  {
    id: 'pixelora_wp_18',
    title: 'Monochrome Geometry',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'clean minimalist architectural angles and pure smooth surfaces with subtle shadow gradation',
    flavor: 'Architectural serenity with balanced negative space tailored for lockscreen widgets.',
    variationIndex: 1,
    timestamp: 1726001700000,
    downloads: 1420,
    tags: ['Architecture', 'Lines', 'Neutral', 'Simplicity'],
  },
  {
    id: 'pixelora_wp_19',
    title: 'Solitary Horizon Glow',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'minimalist calm ocean horizon with subtle sunbeam haze and perfectly balanced gradient',
    flavor: 'Restful minimalist sea expanse providing clear legibility for phone clock and apps.',
    variationIndex: 2,
    timestamp: 1726001800000,
    downloads: 2150,
    tags: ['Sea', 'Horizon', 'Haze', 'Peaceful'],
  },
  {
    id: 'pixelora_wp_20',
    title: 'Dark OLED Radial Eclipse',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'minimalist metallic disc silhouette casting a whisper-thin golden rim light on deep black',
    flavor: 'Sophisticated luxury dark mode aesthetic with ultra-precise geometric poise.',
    variationIndex: 3,
    timestamp: 1726001900000,
    downloads: 3490,
    tags: ['Eclipse', 'OLED Dark', 'Geometric', 'Gold Rim'],
  },

  // ── ABSTRACT (4) ────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_21',
    title: 'Prismatic Liquid Glass',
    category: 'Abstract',
    url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'abstract flowing iridescent liquid glass ribbons with vibrant chromatic caustic refractions',
    flavor: '3D dimensional glass ribbons with prismatic dispersion and smooth specular highlights.',
    variationIndex: 0,
    timestamp: 1726002000000,
    downloads: 3980,
    tags: ['Glass', 'Fluid', '3D', 'Prismatic'],
  },
  {
    id: 'pixelora_wp_22',
    title: 'Molten Amber Topography',
    category: 'Abstract',
    url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'metallic organic topographic wave contours with warm amber and copper metallic reflections',
    flavor: 'Rich metallic sheen with fluid topographic lines and deep shadow recesses.',
    variationIndex: 1,
    timestamp: 1726002100000,
    downloads: 2760,
    tags: ['Metallic', 'Amber', 'Topography', 'Wave'],
  },
  {
    id: 'pixelora_wp_23',
    title: 'Electric Violet Swirls',
    category: 'Abstract',
    url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'macro dynamic fluid acrylic swirl mixing deep violet, cyan, and shimmering gold mica',
    flavor: 'Fluid marbling with rich tactile depth and vibrant chromatic interplay.',
    variationIndex: 2,
    timestamp: 1726002200000,
    downloads: 2210,
    tags: ['Acrylic', 'Fluid Art', 'Violet', 'Cyan'],
  },
  {
    id: 'pixelora_wp_24',
    title: 'Dark Holographic Silk',
    category: 'Abstract',
    url: 'https://images.unsplash.com/photo-1550684847-75bdda21cc95?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'undulating charcoal grey fabric in motion with subtle iridescent holographic sheen',
    flavor: 'Smooth velvety folds with modern sheen and deep contrast for dark mode fans.',
    variationIndex: 3,
    timestamp: 1726002300000,
    downloads: 1890,
    tags: ['Silk', 'Holographic', 'Fabric', 'Moody'],
  },

  // ── MOUNTAINS (3) ───────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_25',
    title: 'Alpine Starlight Ridge',
    category: 'Mountains',
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'snowcapped sharp alpine mountain peaks rising into crystal starry night sky with Milky Way',
    flavor: 'Crisp geological ridges with cold starlight and dramatic alpine elevation.',
    variationIndex: 0,
    timestamp: 1726002400000,
    downloads: 4280,
    tags: ['Alps', 'Snow', 'Stars', 'Summit'],
  },
  {
    id: 'pixelora_wp_26',
    title: 'Dolomites Alpenglow',
    category: 'Mountains',
    url: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'dramatic jagged granite mountain towers glowing in fiery crimson alpenglow sunset',
    flavor: 'Warm sunset lighting illuminating sheer vertical cliff faces with rolling clouds.',
    variationIndex: 1,
    timestamp: 1726002500000,
    downloads: 3100,
    tags: ['Dolomites', 'Alpenglow', 'Sunset', 'Granite'],
  },
  {
    id: 'pixelora_wp_27',
    title: 'Fjord Mist Pinnacles',
    category: 'Mountains',
    url: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'towering glacial sea cliffs and misty mountain fjord with deep emerald waters below',
    flavor: 'Nordic mountain grandeur with atmospheric low-hanging clouds and glassy reflections.',
    variationIndex: 2,
    timestamp: 1726002600000,
    downloads: 2640,
    tags: ['Fjord', 'Nordic', 'Mist', 'Cliffs'],
  },

  // ── GAMING (3) ──────────────────────────────────────────────────────────
  {
    id: 'pixelora_wp_28',
    title: 'Neon Arcade Cyber Glow',
    category: 'Gaming',
    url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '4K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'retro arcade coin-op machines glowing in dark room with cyan and magenta CRT glare',
    flavor: 'Authentic 90s retro gamer nostalgia with vibrant neon CRT luminescence.',
    variationIndex: 0,
    timestamp: 1726002700000,
    downloads: 4620,
    tags: ['Arcade', 'Retro', 'CRT', 'Neon Gaming'],
  },
  {
    id: 'pixelora_wp_29',
    title: 'Mechanical RGB Matrix',
    category: 'Gaming',
    url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'macro angled mechanical keyboard with custom artisan keycaps and per-key RGB backlighting',
    flavor: 'Crisp gamer aesthetic with tactile textures and customizable chromatic glow.',
    variationIndex: 1,
    timestamp: 1726002800000,
    downloads: 3290,
    tags: ['Keyboard', 'RGB', 'Battlestation', 'Hardware'],
  },
  {
    id: 'pixelora_wp_30',
    title: 'Pixel Fantasy Twilight Citadel',
    category: 'Gaming',
    url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1080&h=1920&q=85',
    aspectRatio: '9:16',
    imageSize: '2K',
    modelUsed: 'PIXELORA Studio',
    prompt: 'atmospheric e-sports arena light beams and retro 16-bit gaming mood at twilight',
    flavor: 'Vibrant ambient gaming atmosphere with immersive esports lighting.',
    variationIndex: 2,
    timestamp: 1726002900000,
    downloads: 2850,
    tags: ['Esports', 'Stage', 'Lighting', 'Arena'],
  },
];

export const CATEGORIES_LIST = [
  'All',
  'Nature',
  'Cars',
  'Anime',
  'Space',
  'Minimal',
  'Abstract',
  'Mountains',
  'Gaming',
] as const;
